### ISSUE TITLE
License of mtl_vpu_v0.0.bin

### ISSUE THREAD

**Issue by anthonywong** [intel/linux-vpu-driver#6]
There is a LICENSE.md at the top level directory which is an MIT license. Does it cover `firmware/mtl_vpu_v0.0.bin` as well which is a binary blob?

**Comment by jwludzik** [comment]
MIT does not apply to firmware binaries. I added the license only for firmware binaries in PR #11

**Comment by jwludzik** [comment]
The change has been merged. @anthonywong , I am closing the ticket as done. Please, reopen in case of doubt
